// frontend/src/lib/enums.ts
export enum Industry {
    ECOMMERCE = 'ECOMMERCE',
    FOOD_BEVERAGE = 'FOOD_BEVERAGE',
    TECH_SAAS = 'TECH_SAAS',
    HEALTH_WELLNESS = 'HEALTH_WELLNESS',
    FASHION_BEAUTY = 'FASHION_BEAUTY',
    REAL_ESTATE = 'REAL_ESTATE',
    EDUCATION = 'EDUCATION',
    MARKETING_AGENCY = 'MARKETING_AGENCY',
    OTHER = 'OTHER',
  }